language: java
install: mvn install -PreducedMemory -Dfindbugs.skip=true
script:
    - mvn findbugs:findbugs && mvn javadoc:javadoc
    - mvn cobertura:cobertura -PreducedMemory -DskipTests -Dfindbugs.skip=true
